"""Build supabase/seed/ SQL for provinces, districts and tambons from OCHA HDX COD-AB Thailand.

  uv run python -m admin_boundaries            download (if needed) and write the seed files
  uv run python -m admin_boundaries --check    only report sizes and topology checks

Source: Royal Thai Survey Department via OCHA HDX, "Thailand - Subnational Administrative
Boundaries" (cod-ab-tha), licence CC BY-IGO. P-codes are "TH" + the DOPA code.

Output (decisions, 29 Sep 2026):
- All 77 provinces, simplified to ~500 m for the province selector; the 4 active provinces
  (Pattani, Yala, Narathiwat, Songkhla) also get detailed geometry built from their tambons.
- Districts and tambons of the 4 active provinces: ~10 m ("geom") and ~100 m ("geom_web").
- Tambons are simplified together as one coverage, so neighbours keep identical shared borders
  (no gaps or overlaps); districts and active provinces are unions of those tambons.
"""

from __future__ import annotations

import argparse
import logging
import sys
import urllib.request
import zipfile
from pathlib import Path

import geopandas as gpd
import pyogrio
import shapely
from shapely.geometry import MultiPolygon, Polygon

from ingest_thaiwater.settings import PIPELINE_DIR, REPO_DIR

log = logging.getLogger("admin_boundaries")

GDB_URL = (
    "https://data.humdata.org/dataset/d24bdc45-eb4c-4e3d-8b16-44db02667c27/resource/"
    "ccbf3740-0638-48ea-b612-cdb61ef5462c/download/tha_admin_boundaries.gdb.zip"
)
CACHE = PIPELINE_DIR / ".cache" / "cod-ab"
GDB = CACHE / "tha_admin_boundaries.gdb"
SEED_DIR = REPO_DIR / "supabase" / "seed"

ACTIVE_PROVINCES = {"94": "Pattani", "95": "Yala", "96": "Narathiwat", "90": "Songkhla"}
# Tolerances in degrees (1e-4° ≈ 11 m at 6–7° N).
TOL_DETAIL = 0.0001  # ~10 m
TOL_WEB = 0.001  # ~100 m
TOL_PROVINCE_WEB = 0.005  # ~500 m
DECIMALS = 5  # ~1 m; finer than any tolerance above
BATCH = 40


def download() -> None:
    if GDB.exists():
        return
    CACHE.mkdir(parents=True, exist_ok=True)
    zpath = CACHE / "tha_admin_boundaries.gdb.zip"
    if not zpath.exists():
        log.info("downloading COD-AB (about 175 MB)")
        urllib.request.urlretrieve(GDB_URL, zpath)
    with zipfile.ZipFile(zpath) as z:
        z.extractall(CACHE)


def read_level(level: int) -> gpd.GeoDataFrame:
    df = pyogrio.read_dataframe(GDB, layer=f"tha_admin{level}")
    out = gpd.GeoDataFrame(
        {
            "code": df[f"adm{level}_pcode"].str.removeprefix("TH"),
            "name_en": df[f"adm{level}_name"].str.strip(),
            "name_th": df[f"adm{level}_name1"].str.strip(),
        },
        geometry=df.geometry,
        crs=df.crs,
    )
    if out.crs.to_epsg() != 4326:
        raise SystemExit(f"Unexpected CRS for level {level}: {out.crs}")
    return out


def as_multipolygon(geom):
    geom = shapely.make_valid(geom)
    if geom.geom_type == "GeometryCollection":
        parts = [g for g in geom.geoms if g.geom_type in ("Polygon", "MultiPolygon")]
        geom = shapely.union_all(parts)
    if isinstance(geom, Polygon):
        geom = MultiPolygon([geom])
    return shapely.set_precision(geom, 10**-DECIMALS)


def coverage_simplify(gdf: gpd.GeoDataFrame, tolerance: float) -> gpd.GeoSeries:
    """Simplify a set of polygons that tile an area, keeping shared borders identical."""
    simplified = shapely.coverage_simplify(gdf.geometry.values, tolerance)
    return gpd.GeoSeries([as_multipolygon(g) for g in simplified], index=gdf.index, crs=gdf.crs)


def wkt(geom) -> str:
    return shapely.to_wkt(geom, rounding_precision=DECIMALS, trim=True)


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def write_sql(path: Path, table: str, columns: list[str], rows: list[list[str]], header: str) -> None:
    geo_cols = {"geom", "geom_web"}
    update = ", ".join(f"{c} = excluded.{c}" for c in columns if c != "code")
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        for i in range(0, len(rows), BATCH):
            f.write(f"insert into public.{table} ({', '.join(columns)}) values\n")
            values = []
            for row in rows[i : i + BATCH]:
                cells = [
                    f"extensions.st_geomfromtext({sql_str(v)}, 4326)" if col in geo_cols else v
                    for col, v in zip(columns, row)
                ]
                values.append("  (" + ", ".join(cells) + ")")
            f.write(",\n".join(values))
            f.write(f"\non conflict (code) do update set {update};\n\n")
    log.info("wrote %s (%d rows, %.1f MB)", path.relative_to(REPO_DIR), len(rows), path.stat().st_size / 1e6)


HEADER = (
    "-- Generated by pipeline/admin_boundaries. Do not edit by hand.\n"
    "-- Source: Royal Thai Survey Department via OCHA HDX COD-AB Thailand (CC BY-IGO).\n"
    "-- Simplified for Jaga; not an official boundary product.\n\n"
)


def build(check_only: bool) -> int:
    download()
    prov = read_level(1)
    dist = read_level(2)
    tamb = read_level(3)
    log.info("read %d provinces, %d districts, %d tambons", len(prov), len(dist), len(tamb))
    missing = set(ACTIVE_PROVINCES) - set(prov.code)
    if missing:
        raise SystemExit(f"Active provinces missing from the source: {missing}")

    # Tambons of the active provinces, simplified together.
    t = tamb[tamb.code.str[:2].isin(ACTIVE_PROVINCES)].sort_values("code").reset_index(drop=True)
    t["geom"] = coverage_simplify(t, TOL_DETAIL)
    t["geom_web"] = coverage_simplify(t, TOL_WEB)

    # Topology check: the simplified tambons should not overlap.
    detail = gpd.GeoSeries(t["geom"], crs=4326).to_crs(32647)
    overlap_m2 = detail.area.sum() - shapely.union_all(detail.values).area
    moved = (gpd.GeoSeries(t.geometry, crs=4326).to_crs(32647).area.sum() - detail.area.sum())
    log.info("active tambons: %d; overlap after simplify %.0f m²; area change %.3f%%",
             len(t), overlap_m2, 100 * moved / detail.area.sum())

    # Districts and active provinces: unions of the simplified tambons, so all levels line up.
    d_codes = sorted(t.code.str[:4].unique())
    d_names = dist.set_index("code")
    districts = []
    for code in d_codes:
        part = t[t.code.str[:4] == code]
        districts.append({
            "code": code,
            "name_en": d_names.at[code, "name_en"] if code in d_names.index else code,
            "name_th": d_names.at[code, "name_th"] if code in d_names.index else code,
            "geom": as_multipolygon(shapely.union_all(part["geom"].values)),
            "geom_web": as_multipolygon(shapely.union_all(part["geom_web"].values)),
        })

    prov = prov.sort_values("code").reset_index(drop=True)
    prov["geom_web"] = coverage_simplify(prov, TOL_PROVINCE_WEB)
    prov["geom_detail"] = prov["geom_web"]
    for i, row in prov.iterrows():
        if row.code in ACTIVE_PROVINCES:
            part = t[t.code.str[:2] == row.code]
            prov.at[i, "geom_detail"] = as_multipolygon(shapely.union_all(part["geom"].values))

    if check_only:
        return 0

    SEED_DIR.mkdir(parents=True, exist_ok=True)
    write_sql(
        SEED_DIR / "10_provinces.sql", "provinces",
        ["code", "name_th", "name_en", "status", "geom", "geom_web"],
        [[sql_str(r.code), sql_str(r.name_th), sql_str(r.name_en),
          "'active'" if r.code in ACTIVE_PROVINCES else "'coming_soon'",
          wkt(r.geom_detail), wkt(r.geom_web)] for r in prov.itertuples()],
        HEADER + "-- All 77 provinces; Pattani, Yala, Narathiwat and Songkhla are active.\n\n",
    )
    write_sql(
        SEED_DIR / "20_districts.sql", "districts",
        ["code", "province_code", "name_th", "name_en", "geom", "geom_web"],
        [[sql_str(d["code"]), sql_str(d["code"][:2]), sql_str(d["name_th"]), sql_str(d["name_en"]),
          wkt(d["geom"]), wkt(d["geom_web"])] for d in districts],
        HEADER + "-- Districts of the 4 active provinces (unions of their simplified tambons).\n\n",
    )
    write_sql(
        SEED_DIR / "30_tambons.sql", "tambons",
        ["code", "district_code", "province_code", "name_th", "name_en", "geom", "geom_web"],
        [[sql_str(r.code), sql_str(r.code[:4]), sql_str(r.code[:2]), sql_str(r.name_th),
          sql_str(r.name_en), wkt(r.geom), wkt(r.geom_web)] for r in t.itertuples()],
        HEADER + "-- Tambons of the 4 active provinces: geom ~10 m, geom_web ~100 m.\n\n",
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    ap = argparse.ArgumentParser(prog="admin_boundaries", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="only report sizes and topology checks")
    return build(ap.parse_args(argv).check)


if __name__ == "__main__":
    sys.exit(main())
